#!/usr/bin/python3.6
import sys, os, json, argparse, urllib, requests
from urllib.error import HTTPError, URLError
from socket import timeout

URL = "https://api.guildwars2.com/v2/"
API_KEY = "?access_token="
TAB_SIZE = 30

def load_api_key():
	try:
		with open("api_key", 'r') as key_file:
			global API_KEY
			API_KEY = API_KEY + key_file.readline().rstrip()
	except OSError:
		exit("could not read api_key")

def url2json(target_url):
	try:
		response = requests.get(target_url, timeout=10).text
	except HTTPError as error:
		logging.error('Data of %s not retrieved because %s\nURL: %s', name, error, url)
	except URLError as error:
		if isinstance(error.reason, timeout):
			logging.error('socket timed out - URL %s', url)
		else:
			logging.error('some other error happened')
	else:
		return json.loads(response)

def extract_values(items, value):
	values = []
	for item in items:
		if item is not None:
			values.append(str(item[value]))
	return values

def get_characters():
	return url2json(URL + "characters" + API_KEY)


def get_list(list_type, items):
	return url2json(URL + list_type + "?ids=" + ",".join(items))

def print_item(item):
	# Todo: consumables do not have rarities
	print("{} \nLink: {} Rarity: {}\n".format(item['name'], item['chat_link'], item['rarity']))

def find_character(substring):
	char_list = get_characters()
	character = ""
	chars_found = 0
	for char in char_list:
		if substring.lower() in str(char).lower():
			character = str(char)
			chars_found += 1
	if chars_found == 0:
		exit("character not found")
	if chars_found > 1:
		exit("found {} characters".format(chars_found))

	print("found character: {}".format(character))
	return character
	

def inventory(args):
	if len(args) < 1:
		exit("Usage: gw2tool inventory <character>")

	character = find_character(args[0])

	# urllib.parse.quote to handle spaces in character names (firstname lastname) and weird letters?
	inventory = url2json(URL + "characters/" + urllib.parse.quote(character) + "/inventory" + API_KEY)
	
	item_ids = []
	item_amounts = []

	for bag in inventory['bags']:
		for item in bag['inventory']:
			if item is not None:
				item_ids.append(str(item['id']))
				item_amounts.append(str(item['count']))
	inventory_items = get_list("items", item_ids) 
	
	index = 0
	for item in inventory_items:
		print("{}x {}".format(item_amounts[index], item['name']))
		index += 1

def equipment(args):
	print("equipment")
	if len(args) < 1:
		exit("Usage: gw2tool equipment <character>")

	character = find_character(args[0])
	char_equipment = url2json(URL + "characters/" + urllib.parse.quote(character) + "/equipment" + API_KEY)
	item_slots = extract_values(char_equipment['equipment'], 'slot')
	equipment_items = get_list("items", extract_values(char_equipment['equipment'], 'id'))

	index = 0
	for item in equipment_items:
		print("{}: ".format(item_slots[index]), end='')
		print_item(item)
		index += 1

def print_tab(bank_items, tab_index):
	item_ids = []
	item_amounts = []
	# print intervals: 0-29, 30-59, 60-89, etc
	for i in range(tab_index*TAB_SIZE, (tab_index*TAB_SIZE)+TAB_SIZE):
		if bank_items[i] is not None:
			item_ids.append(str(bank_items[i]['id']))
			item_amounts.append(bank_items[i]['count'])
	tab_items = get_list("items", item_ids)
	index = 0
	for item in tab_items:
		print("{}x {}".format(item_amounts[index], item['name'])) 
		index += 1


def bank(args):
	tab_list = []
	if len(args) > 0:
		tab_list = [int(s) for s in args if s.isdigit()]
		if not tab_list:
			print("Usage: gw2tool bank (<bank_tab>)")
	
	bank_items = url2json(URL + "account/bank" + API_KEY)
	tab_num = int(len(bank_items) / TAB_SIZE)

	if not tab_list:
		for i in range(0, tab_num):
			print_tab(bank_items, i)
			print("")
	else:
		for index in tab_list:
			print_tab(bank_items, index)
			print("")


def account(args):
	print("account TODO")


def list_things(args):
	if len(args) < 1:
		exit("Usage: gw2tool list <parameter(s)>")
	
	if str(args[0]) == "characters":
		print(*get_characters(), sep='\n')


def daily(args):
	if len(args) < 1:
		exit("Usage: gw2tool daily <parameter(s)>")
	
	daily_achievements = url2json(URL + "achievements/daily")
	
	if str(args[0]) == "fractals":
		daily_fractals = daily_achievements['fractals']
		achievement_items = get_list("achievements", extract_values(daily_fractals, 'id'))
		
		names = []
		for achievement in achievement_items:
			name = achievement['name']
			if "Tier 4" in name:
				names.append("Daily" + name.split('4')[-1])
			if "Rec" in achievement['name']:
				names.append("Rec " + name.split()[-1])
		for name in names:
			print(name)

def main():
	
	commands = {
		'inventory': inventory,
		'equipment': equipment,
		'bank': bank,
		'account': account,
		'list': list_things,
		'daily': daily,
		}
	
	if len(sys.argv) < 2:
		exit("Usage: gw2tool <command> <parameter(s)>")

	if not sys.argv[1] in commands.keys():
		exit("Command not found")

	load_api_key()
	commands[sys.argv[1]](sys.argv[2:])

if __name__ == "__main__":
		main()
